name: Build Inception-AHD-Recommender

on:
  push:
    branches:
      - master
    paths:
      - inception_ahd_recommender/**

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker compose -f compose.yml build ahd-deid-recommender
