name: Build and publish Inception-AHD-Recommender

on:
  push:
    branches:
      - main
    paths:
      - inception_ahd_recommender/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: inception-ahd-recommender

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # automatically generiert

      - name: Extract image tag from docker-compose.yml
        id: extract-tag
        run: |
          # Extract version from docker-compose.yml
          TAG=$(grep 'image: ahd-deid-recommender' docker-compose.yml | sed 's/.*://')
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./inception_ahd_recommender
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
